### ISSUE TITLE
Fix hodgepodge plugin attribute

### ISSUE THREAD

**Issue by devinivy** [hapipal/hodgepodge#2]
The `hodgepodge` plugin attribute used to cause failure of plugin registration when present, which was desirable.  As of some hapi version (that hodgepodge supports), this is no longer the case.  Suggested,

``` js
plugin.attributes = {
    name: 'some-name',
    dependencies: { hodgepodge: true }
};
```

or

``` js
plugin.attributes = {
    name: 'some-name',
    dependencies: { hodgepodge: [list, of, deps] }
};
```

**Comment by aymericbeaumet** [comment]
Hum, I don't like `hodgepodge` being too intrusive. Maybe something along the lines of:

``` js
plugin.attributes = {
    name: 'some-name',
    dependencies: () => ['a', 'b', 'c']
};
```

Hapi will throw as the type doesn't match, still the semantic stays close.
